# Set these if not present
title: AlanHacks
description: Pentesting write-ups, WAF research, and HTB walkthroughs.
# If your site is served from a subpath, set baseurl:
# baseurl: "/alanhacksthings.github.io" # example only; leave blank if root
